source 'https://rubygems.org'

gem 'rails', '~> 5.2.1'
gem 'bcrypt', '~> 3.1.7'
gem 'pg'
gem 'bootsnap'
gem 'aasm'
gem 'faker'
gem 'where_exists'
gem 'byebug'
gem 'nullalign'
gem 'ancestry'
gem 'closure_tree'
