development:
  adapter: postgresql
  username: wka
  database: critic_development
  template: template0
  port: 5432
  host: localhost

test:
  adapter: postgresql
  username: wka
  database: critic_test
  template: template0
  port: 5432
  host: localhost

