# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 690eb707a74890553a84437b0f98ceaab97d037f20240cead576d6bc869dcdd8978cf3caad6439c916d14ad05fef79cd8a3c1ecf3a7c376137c5e16d8094be5c

test:
  secret_key_base: 4e5d1104993be798580bc2a912e29084ff130e67d20dbf944819c3e6f27533e2dea36024083f0bc56952aa11a56c051e5376b835765689236735675f738f394d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
